### ISSUE TITLE
Implement Main

### ISSUE THREAD

**Issue by Gnormelli** [kth-ii1302-vt22-group-3/iot#40]
### SubTasks
- [x] Code so that sensor reads periodically 
- [x] Send values to Server

### Acceptance Criteria
- [x] Receive values by interval in DB

**Comment by WilleNord** [comment]
Acceptance criteria fulfilled!

**Comment by WilleNord** [comment]
Refactored
