### ISSUE TITLE
Implement UART - receive

### ISSUE THREAD

**Issue by Natashlab** [kth-ii1302-vt22-group-3/iot#45]
### SubTasks
- [ ] Receive variable length
- [ ] Implement with Wifi-module

### Acceptance Criteria
- [ ] Can enter different lengths of messages
- [ ] Message received in STM correctly
